const Medicine = require('../models/Medicine');
const mongoose = require('mongoose');

const medicineData = [
  // Pain Relief
  {
    name: 'Paracetamol 500mg',
    genericName: 'Acetaminophen',
    brand: 'DemoPharma',
    category: 'Pain Relief',
    description: 'Demo pain reliever for headaches, muscle aches, and fever. Consult a qualified medical professional before use.',
    price: 5.99,
    mrp: 7.99,
    discountPercent: 25,
    stock: 100,
    unit: 'tablet',
    requiresPrescription: false,
    manufacturer: 'DemoPharma Ltd',
    expiryInfo: 'Dec 2028',
    isAvailable: true,
    rating: 4.5,
    reviewCount: 128,
  },
  {
    name: 'Ibuprofen 400mg',
    genericName: 'Ibuprofen',
    brand: 'DemoPharma',
    category: 'Pain Relief',
    description: 'Demo anti-inflammatory for pain relief. Consult a qualified medical professional before use.',
    price: 8.49,
    mrp: 10.99,
    discountPercent: 23,
    stock: 75,
    unit: 'tablet',
    requiresPrescription: false,
    manufacturer: 'DemoPharma Ltd',
    expiryInfo: 'Jan 2029',
    isAvailable: true,
    rating: 4.3,
    reviewCount: 95,
  },
  {
    name: 'Aspirin 100mg',
    genericName: 'Aspirin',
    brand: 'DemoPharma',
    category: 'Pain Relief',
    description: 'Demo pain reliever and blood thinner. Consult a qualified medical professional before use.',
    price: 4.49,
    mrp: 5.99,
    discountPercent: 25,
    stock: 120,
    unit: 'tablet',
    requiresPrescription: false,
    manufacturer: 'DemoPharma Ltd',
    expiryInfo: 'Mar 2029',
    isAvailable: true,
    rating: 4.4,
    reviewCount: 87,
  },

  // Cold & Cough
  {
    name: 'Cough Syrup',
    genericName: 'Dextromethorphan',
    brand: 'DemoPharma',
    category: 'Cold & Cough',
    description: 'Demo cough suppressant for dry cough. Consult a qualified medical professional before use.',
    price: 8.49,
    mrp: 9.99,
    discountPercent: 15,
    stock: 60,
    unit: 'bottle',
    requiresPrescription: false,
    manufacturer: 'DemoPharma Ltd',
    expiryInfo: 'Nov 2028',
    isAvailable: true,
    rating: 4.3,
    reviewCount: 72,
  },
  {
    name: 'Cold Relief Tablets',
    genericName: 'Paracetamol + Phenylephrine',
    brand: 'DemoPharma',
    category: 'Cold & Cough',
    description: 'Demo cold and flu relief tablets. Consult a qualified medical professional before use.',
    price: 6.99,
    mrp: 8.99,
    discountPercent: 22,
    stock: 85,
    unit: 'tablet',
    requiresPrescription: false,
    manufacturer: 'DemoPharma Ltd',
    expiryInfo: 'Feb 2029',
    isAvailable: true,
    rating: 4.2,
    reviewCount: 64,
  },
  {
    name: 'Nasal Drops',
    genericName: 'Oxymetazoline',
    brand: 'DemoPharma',
    category: 'Cold & Cough',
    description: 'Demo nasal decongestant drops. Consult a qualified medical professional before use.',
    price: 5.49,
    mrp: 6.99,
    discountPercent: 21,
    stock: 90,
    unit: 'drops',
    requiresPrescription: false,
    manufacturer: 'DemoPharma Ltd',
    expiryInfo: 'Apr 2029',
    isAvailable: true,
    rating: 4.1,
    reviewCount: 58,
  },

  // Vitamins
  {
    name: 'Vitamin C 1000mg',
    genericName: 'Ascorbic Acid',
    brand: 'DemoPharma',
    category: 'Vitamins',
    description: 'Demo vitamin C supplement for immune support. Consult a qualified medical professional before use.',
    price: 12.99,
    mrp: 15.99,
    discountPercent: 19,
    stock: 150,
    unit: 'tablet',
    requiresPrescription: false,
    manufacturer: 'DemoPharma Ltd',
    expiryInfo: 'Jun 2029',
    isAvailable: true,
    rating: 4.8,
    reviewCount: 156,
  },
  {
    name: 'Vitamin D3 1000 IU',
    genericName: 'Cholecalciferol',
    brand: 'DemoPharma',
    category: 'Vitamins',
    description: 'Demo vitamin D3 supplement for bone health. Consult a qualified medical professional before use.',
    price: 9.99,
    mrp: 12.99,
    discountPercent: 23,
    stock: 130,
    unit: 'capsule',
    requiresPrescription: false,
    manufacturer: 'DemoPharma Ltd',
    expiryInfo: 'Jul 2029',
    isAvailable: true,
    rating: 4.6,
    reviewCount: 112,
  },
  {
    name: 'Multivitamin Tablets',
    genericName: 'Multivitamin Complex',
    brand: 'DemoPharma',
    category: 'Vitamins',
    description: 'Demo daily multivitamin supplement. Consult a qualified medical professional before use.',
    price: 14.99,
    mrp: 18.99,
    discountPercent: 21,
    stock: 110,
    unit: 'tablet',
    requiresPrescription: false,
    manufacturer: 'DemoPharma Ltd',
    expiryInfo: 'Aug 2029',
    isAvailable: true,
    rating: 4.5,
    reviewCount: 98,
  },

  // First Aid
  {
    name: 'Antiseptic Cream',
    genericName: 'Chlorhexidine',
    brand: 'DemoPharma',
    category: 'First Aid',
    description: 'Demo antiseptic cream for minor cuts and wounds. Consult a qualified medical professional before use.',
    price: 6.99,
    mrp: 8.99,
    discountPercent: 22,
    stock: 80,
    unit: 'tube',
    requiresPrescription: false,
    manufacturer: 'DemoPharma Ltd',
    expiryInfo: 'Sep 2029',
    isAvailable: true,
    rating: 4.6,
    reviewCount: 89,
  },
  {
    name: 'Bandage Pack',
    genericName: 'Sterile Bandages',
    brand: 'DemoPharma',
    category: 'First Aid',
    description: 'Demo sterile bandage pack for wound care. Consult a qualified medical professional before use.',
    price: 4.99,
    mrp: 6.49,
    discountPercent: 23,
    stock: 95,
    unit: 'pack',
    requiresPrescription: false,
    manufacturer: 'DemoPharma Ltd',
    expiryInfo: 'Oct 2029',
    isAvailable: true,
    rating: 4.4,
    reviewCount: 76,
  },
  {
    name: 'Cotton Roll',
    genericName: 'Absorbent Cotton',
    brand: 'DemoPharma',
    category: 'First Aid',
    description: 'Demo absorbent cotton roll for wound dressing. Consult a qualified medical professional before use.',
    price: 3.49,
    mrp: 4.49,
    discountPercent: 22,
    stock: 100,
    unit: 'pack',
    requiresPrescription: false,
    manufacturer: 'DemoPharma Ltd',
    expiryInfo: 'Nov 2029',
    isAvailable: true,
    rating: 4.3,
    reviewCount: 65,
  },

  // Diabetes Care
  {
    name: 'Blood Glucose Test Strips',
    genericName: 'Glucose Test Strips',
    brand: 'DemoPharma',
    category: 'Diabetes Care',
    description: 'Demo blood glucose test strips. Consult a qualified medical professional before use.',
    price: 24.99,
    mrp: 29.99,
    discountPercent: 17,
    stock: 70,
    unit: 'pack',
    requiresPrescription: false,
    manufacturer: 'DemoPharma Ltd',
    expiryInfo: 'Dec 2029',
    isAvailable: true,
    rating: 4.5,
    reviewCount: 82,
  },
  {
    name: 'Insulin Syringes',
    genericName: 'Disposable Syringes',
    brand: 'DemoPharma',
    category: 'Diabetes Care',
    description: 'Demo disposable insulin syringes. Consult a qualified medical professional before use.',
    price: 12.99,
    mrp: 15.99,
    discountPercent: 19,
    stock: 85,
    unit: 'pack',
    requiresPrescription: false,
    manufacturer: 'DemoPharma Ltd',
    expiryInfo: 'Jan 2030',
    isAvailable: true,
    rating: 4.4,
    reviewCount: 68,
  },

  // Heart Care
  {
    name: 'Omega-3 Fish Oil',
    genericName: 'Omega-3 Fatty Acids',
    brand: 'DemoPharma',
    category: 'Heart Care',
    description: 'Demo omega-3 fish oil supplement for heart health. Consult a qualified medical professional before use.',
    price: 18.99,
    mrp: 23.99,
    discountPercent: 21,
    stock: 90,
    unit: 'capsule',
    requiresPrescription: false,
    manufacturer: 'DemoPharma Ltd',
    expiryInfo: 'Feb 2030',
    isAvailable: true,
    rating: 4.6,
    reviewCount: 94,
  },
  {
    name: 'Aspirin Low Dose',
    genericName: 'Aspirin 81mg',
    brand: 'DemoPharma',
    category: 'Heart Care',
    description: 'Demo low dose aspirin for heart health. Consult a qualified medical professional before use.',
    price: 7.99,
    mrp: 9.99,
    discountPercent: 20,
    stock: 110,
    unit: 'tablet',
    requiresPrescription: false,
    manufacturer: 'DemoPharma Ltd',
    expiryInfo: 'Mar 2030',
    isAvailable: true,
    rating: 4.5,
    reviewCount: 78,
  },

  // Skin Care
  {
    name: 'Moisturizing Lotion',
    genericName: 'Emollient Lotion',
    brand: 'DemoPharma',
    category: 'Skin Care',
    description: 'Demo moisturizing lotion for dry skin. Consult a qualified medical professional before use.',
    price: 11.99,
    mrp: 14.99,
    discountPercent: 20,
    stock: 75,
    unit: 'bottle',
    requiresPrescription: false,
    manufacturer: 'DemoPharma Ltd',
    expiryInfo: 'Apr 2030',
    isAvailable: true,
    rating: 4.4,
    reviewCount: 86,
  },
  {
    name: 'Antibiotic Ointment',
    genericName: 'Bacitracin',
    brand: 'DemoPharma',
    category: 'Skin Care',
    description: 'Demo antibiotic ointment for minor skin infections. Consult a qualified medical professional before use.',
    price: 8.99,
    mrp: 11.99,
    discountPercent: 25,
    stock: 65,
    unit: 'tube',
    requiresPrescription: false,
    manufacturer: 'DemoPharma Ltd',
    expiryInfo: 'May 2030',
    isAvailable: true,
    rating: 4.3,
    reviewCount: 72,
  },

  // Digestive Care
  {
    name: 'Antacid Tablets',
    genericName: 'Calcium Carbonate',
    brand: 'DemoPharma',
    category: 'Digestive Care',
    description: 'Demo antacid tablets for heartburn relief. Consult a qualified medical professional before use.',
    price: 5.99,
    mrp: 7.49,
    discountPercent: 20,
    stock: 100,
    unit: 'tablet',
    requiresPrescription: false,
    manufacturer: 'DemoPharma Ltd',
    expiryInfo: 'Jun 2030',
    isAvailable: true,
    rating: 4.5,
    reviewCount: 91,
  },
  {
    name: 'Probiotic Capsules',
    genericName: 'Lactobacillus',
    brand: 'DemoPharma',
    category: 'Digestive Care',
    description: 'Demo probiotic capsules for digestive health. Consult a qualified medical professional before use.',
    price: 16.99,
    mrp: 20.99,
    discountPercent: 19,
    stock: 80,
    unit: 'capsule',
    requiresPrescription: false,
    manufacturer: 'DemoPharma Ltd',
    expiryInfo: 'Jul 2030',
    isAvailable: true,
    rating: 4.6,
    reviewCount: 84,
  },

  // Personal Care
  {
    name: 'Hand Sanitizer',
    genericName: 'Alcohol-based Sanitizer',
    brand: 'DemoPharma',
    category: 'Personal Care',
    description: 'Demo hand sanitizer for hand hygiene. Consult a qualified medical professional before use.',
    price: 4.99,
    mrp: 6.49,
    discountPercent: 23,
    stock: 120,
    unit: 'bottle',
    requiresPrescription: false,
    manufacturer: 'DemoPharma Ltd',
    expiryInfo: 'Aug 2030',
    isAvailable: true,
    rating: 4.4,
    reviewCount: 105,
  },
  {
    name: 'Face Mask Pack',
    genericName: 'Disposable Face Masks',
    brand: 'DemoPharma',
    category: 'Personal Care',
    description: 'Demo disposable face masks. Consult a qualified medical professional before use.',
    price: 7.99,
    mrp: 9.99,
    discountPercent: 20,
    stock: 95,
    unit: 'pack',
    requiresPrescription: false,
    manufacturer: 'DemoPharma Ltd',
    expiryInfo: 'Sep 2030',
    isAvailable: true,
    rating: 4.3,
    reviewCount: 88,
  },

  // Baby Care
  {
    name: 'Baby Diapers',
    genericName: 'Disposable Diapers',
    brand: 'DemoPharma',
    category: 'Baby Care',
    description: 'Demo disposable baby diapers. Consult a qualified medical professional before use.',
    price: 19.99,
    mrp: 24.99,
    discountPercent: 20,
    stock: 70,
    unit: 'pack',
    requiresPrescription: false,
    manufacturer: 'DemoPharma Ltd',
    expiryInfo: 'N/A',
    isAvailable: true,
    rating: 4.5,
    reviewCount: 92,
  },
  {
    name: 'Baby Lotion',
    genericName: 'Baby Moisturizer',
    brand: 'DemoPharma',
    category: 'Baby Care',
    description: 'Demo baby moisturizing lotion. Consult a qualified medical professional before use.',
    price: 8.99,
    mrp: 10.99,
    discountPercent: 18,
    stock: 85,
    unit: 'bottle',
    requiresPrescription: false,
    manufacturer: 'DemoPharma Ltd',
    expiryInfo: 'Oct 2030',
    isAvailable: true,
    rating: 4.6,
    reviewCount: 79,
  },

  // Health Devices
  {
    name: 'Digital Thermometer',
    genericName: 'Digital Thermometer',
    brand: 'DemoPharma',
    category: 'Health Devices',
    description: 'Demo digital thermometer for temperature measurement. Consult a qualified medical professional before use.',
    price: 15.99,
    mrp: 19.99,
    discountPercent: 20,
    stock: 60,
    unit: 'box',
    requiresPrescription: false,
    manufacturer: 'DemoPharma Ltd',
    expiryInfo: 'N/A',
    isAvailable: true,
    rating: 4.7,
    reviewCount: 108,
  },
  {
    name: 'Blood Pressure Monitor',
    genericName: 'Digital BP Monitor',
    brand: 'DemoPharma',
    category: 'Health Devices',
    description: 'Demo digital blood pressure monitor. Consult a qualified medical professional before use.',
    price: 34.99,
    mrp: 44.99,
    discountPercent: 22,
    stock: 45,
    unit: 'box',
    requiresPrescription: false,
    manufacturer: 'DemoPharma Ltd',
    expiryInfo: 'N/A',
    isAvailable: true,
    rating: 4.6,
    reviewCount: 96,
  },
];

const seedMedicines = async () => {
  try {
    console.log('Starting medicine seed...');
    
    // Check if medicines already exist
    const existingCount = await Medicine.countDocuments();
    if (existingCount > 0) {
      console.log(`Medicines already exist (${existingCount} found). Skipping seed.`);
      return;
    }

    // Insert medicines
    await Medicine.insertMany(medicineData);
    console.log(`Successfully seeded ${medicineData.length} medicines.`);
  } catch (error) {
    console.error('Error seeding medicines:', error.message);
    throw error;
  }
};

module.exports = seedMedicines;
