class AppRoutes {
  AppRoutes._();

  static const String splash = '/splash';
  static const String login = '/login';
  static const String register = '/register';
  static const String home = '/home';
  static const String appointments = '/appointments';
  static const String emergency = '/emergency';
  static const String pharmacy = '/pharmacy';
  static const String profile = '/profile';
  static const String settings = '/settings';
  static const String forgotPassword = '/forgot-password';
  static const String otpVerification = '/otp-verification';
  static const String resetPassword = '/reset-password';
  static const String doctorList = '/doctor-list';
  static const String doctorDetails = '/doctor-details';
  static const String bookAppointment = '/book-appointment';
  static const String appointmentConfirmation = '/appointment-confirmation';
  static const String emergencyHome = '/emergency-home';
  static const String ambulanceRequest = '/ambulance-request';
  static const String emergencyContacts = '/emergency-contacts';
  static const String firstAid = '/first-aid';
  static const String pharmacyHome = '/pharmacy-home';
  static const String medicineDetails = '/medicine-details';
  static const String pharmacyCart = '/pharmacy-cart';
  static const String prescription = '/prescription';
  static const String pharmacyOrderConfirmation = '/pharmacy-order-confirmation';
  static const String editProfile = '/edit-profile';
  static const String medicalInformation = '/medical-information';
  static const String notificationSettings = '/notification-settings';
  static const String privacySecurity = '/privacy-security';
  static const String helpSupport = '/help-support';
  static const String about = '/about';
  static const String medicalRecords = '/medical-records';
  static const String medicalRecordDetails = '/medical-record-details';
  static const String prescriptionRecords = '/prescription-records';
  static const String labReports = '/lab-reports';
  static const String doctorReports = '/doctor-reports';
}
